Update patch set 4
Patch Set 4:

I'm retriggering gate_midonet-bgp_mdts because of the following ping errors, which seem errors happen in Jenkins rather than what is caused by this patch.

Test Result (4 failures / ±0)
mdts.tests.functional_tests.test_bgp.test_icmp_failback (with_bindings connected to uplink #1)
mdts.tests.functional_tests.test_bgp.test_icmp_failback (with_bindings connected to uplink #2)

Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 348, in test_icmp_failback
    ping_inet() # BGP #1 is lost
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 223, in ping_inet
    ping_inet(count, interval, retry, retry_count - 1, port)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 223, in ping_inet
    ping_inet(count, interval, retry, retry_count - 1, port)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 225, in ping_inet
    raise AssertionError(e.cmd, e.returncode)
AssertionError: ("('ip netns exec ns-if-0001-001 ping -i 1 -c 3 -s 56 1.1.1.1', 'PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.\\n\\n--- 1.1.1.1 ping statistics ---\\n3 packets transmitted, 0 received, 100% packet loss, time 2016ms\\n\\n', '')", 1)

Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 348, in test_icmp_failback
    ping_inet() # BGP #1 is lost
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 223, in ping_inet
    ping_inet(count, interval, retry, retry_count - 1, port)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 223, in ping_inet
    ping_inet(count, interval, retry, retry_count - 1, port)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 225, in ping_inet
    raise AssertionError(e.cmd, e.returncode)
AssertionError: ("('ip netns exec ns-if-0002-001 ping -i 1 -c 3 -s 56 1.1.1.1', 'PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.\\n\\n--- 1.1.1.1 ping statistics ---\\n3 packets transmitted, 0 received, 100% packet loss, time 1999ms\\n\\n', '')", 1)

Patch-set: 4
Reviewer: Taku Fukushima <1002743@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=0