Modify timout for each actor to be longer
This patch modifies the timeout for stopping each actor longer
from 100 milliseconds to 200 milliseconds because we often get
the following error log when we stop midolman. The timeout for
stopping all actors is also modifed using the timeout for each
actor accordingly.

2014.11.07 15:17:59.951 ERROR [Thread-1] MidolmanActorsService -  Failed to gracefully stop all actors
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://midolman/user/midolman#-1993850003]] after [100 ms]
        at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333) ~[akka-actor_2.11-2.3.6.jar:na]
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[akka-actor_2.11-2.3.6.jar:na]
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[scala-library-2.11.2.jar:na]
        at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[scala-library-2.11.2.jar:na]
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[scala-library-2.11.2.jar:na]
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467) ~[akka-actor_2.11-2.3.6.jar:na]
        at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419) ~[akka-actor_2.11-2.3.6.jar:na]
        at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423) ~[akka-actor_2.11-2.3.6.jar:na]
        at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375) ~[akka-actor_2.11-2.3.6.jar:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_65]

This is related with MN-3021.

Change-Id: I907b10d7b3ab289736782a38c4d6b32a66dcc6fc
Signed-off-by: Taku Fukushima <tfukushima@midokura.com>