Update patch set 1
Patch Set 1:

It seems Midokura Bot is failing because of the Jenkins issue rather than tests. So I'm submitting this again.

Error: Unable to read from data file /home/jenkins/workspace/gerrit-unit-gate/633/odp/build/cobertura/cobertura.ser

Patch-set: 1
Reviewer: Taku Fukushima <1002743@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=0