Revert "Use scala def xxx() {} syntax for methods returning Unit (void)"
This reverts commit 68d68c11bcca13c7e1fae5d70e03baa70ad52b0b.

The commit caused the following exception that broke BGP
functionality.

Exception in thread "main" java.lang.NoSuchMethodError: com.midokura.midolman.quagga.ZebraServer.start()Lscala/actors/Actor;
	  at com.midokura.midolman.layer3.BgpPortService.start(BgpPortService.java:235)
	  at com.midokura.midolman.layer3.NetworkController$1.run(NetworkController.java:1232)
2011.10.09 09:03:29,403DEBUG BaseProtocolImpl - pending operation 1 not found
	   at com.midokura.midolman.layer3.NetworkController.addServicePort(NetworkController.java:1261)
	   at com.midokura.midolman.layer3.NetworkController.addPort(NetworkController.java:1280)
	   at com.midokura.midolman.AbstractController.callAddPort(AbstractController.java:177)
	   at com.midokura.midolman.AbstractController.onConnectionMade(AbstractController.java:126)
	   at com.midokura.midolman.ControllerTrampoline.onConnectionMade(ControllerTrampoline.java:236)
	   at com.midokura.midolman.openflow.ControllerStubImpl$3.onSuccess(ControllerStubImpl.java:143)
	   at com.midokura.midolman.openflow.ControllerStubImpl$3.onSuccess(ControllerStubImpl.java:135)
	   at com.midokura.midolman.openflow.ControllerStubImpl.handleMessage(ControllerStubImpl.java:189)
	   at com.midokura.midolman.openflow.BaseProtocolImpl.handleEvent(BaseProtocolImpl.java:189)2011.10.09 09:03:29,403DEBUG BaseProtocolImpl - pending operation 2 not found

	   at com.midokura.midolman.eventloop.SelectLoop.doLoop(SelectLoop.java:120)
	   at com.midokura.midolman.Midolman.run(Midolman.java:112)
	   at com.midokura.midolman.Midolman.main(Midolman.java:179)