Update patch set 4
Patch Set 4: Code-Review-1

(2 comments)

I'm not sure whether this is related to this patch, but the unit test seems flaky. For me at least, it failed with:

org.scalatest.exceptions.TestFailedException: [LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray()], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray(VIP [id=c6d44ee1-c97f-4226-8b5b-fb4753b3acf1 adminStateUp=true poolId=a64fdd52-cc5d-4155-9676-b541345513e2 address=192.168.0.1 port=7777 isStickySourceIp=false])], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray(VIP [id=c6d44ee1-c97f-4226-8b5b-fb4753b3acf1 adminStateUp=false poolId=a64fdd52-cc5d-4155-9676-b541345513e2 address=192.168.0.1 port=7777 isStickySourceIp=false])], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray(VIP [id=c6d44ee1-c97f-4226-8b5b-fb4753b3acf1 adminStateUp=false poolId=a64fdd52-cc5d-4155-9676-b541345513e2 address=192.168.0.1 port=7777 isStickySourceIp=false], VIP [id=c40a8f42-47a0-4ad8-9579-d77601f1b64c adminStateUp=true poolId=98cbfc9d-add9-44f3-a57a-2ae8ee341753 address=192.168.0.2 port=7777 isStickySourceIp=false])], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray(VIP [id=c40a8f42-47a0-4ad8-9579-d77601f1b64c adminStateUp=true poolId=98cbfc9d-add9-44f3-a57a-2ae8ee341753 address=192.168.0.2 port=7777 isStickySourceIp=false])], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray()], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=true routerId=null vips=WrappedArray(VIP [id=c40a8f42-47a0-4ad8-9579-d77601f1b64c adminStateUp=true poolId=10647272-43d6-4a1b-a0e2-5ac3285f38cd address=192.168.0.2 port=7777 isStickySourceIp=false])], LoadBalancer [id=056f110b-3f84-4288-aa57-5cfab8f1bd51 adminStateUp=false routerId=null vips=WrappedArray()]] had size 8 instead of expected size 7

Otherwise, the change to the mapper is okay.

Patch-set: 4
Label: Code-Review=-1