PMC: Remove protobuf dependency
It seems protobuf compiler and runtime mismatch causes
import time errors like:

      File "/usr/lib/python2.7/dist-packages/midonetclient/topology/_protobuf/topology_api_pb2.py", line 10, in <module>
        from google.protobuf import symbol_database as _symbol_database
    ImportError: cannot import name symbol_database

Given that neutron lbaas v2 driver is going to switch
from the topology api to the rest api, remove the
dependency for now to avoid the troubles.

Signed-off-by: YAMAMOTO Takashi <yamamoto@midokura.com>
Change-Id: I3d396b31b0ae33c47a5de83af3e1b335a79cf826
(cherry picked from commit e861a53434c0707857e1a31f4a84e46ed2c11813)