Update patch set 6
Patch Set 6:

There're ERRORs in MDTS logs. But I'm not sure if it's caused by this patch:

  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 348, in test_icmp_failback
    ping_inet() # BGP #1 is lost
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 223, in ping_inet
    ping_inet(count, interval, retry, retry_count - 1, port)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 223, in ping_inet
    ping_inet(count, interval, retry, retry_count - 1, port)
  File "/home/jenkins/workspace/gate_midonet_bgp_mdts/midonet/tests/mdts/tests/functional_tests/test_bgp.py", line 225, in ping_inet
    raise AssertionError(e.cmd, e.returncode)
'("(\'ip netns exec ns-if-0002-001 ping -i 1 -c 3 -s 56 1.1.1.1\', \'PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.\\\\n\\\\n--- 1.1.1.1 ping statistics ---\\\\n3 packets transmitted, 0 received, 100% packet loss, time 2017ms\\\\n\\\\n\', \'\')", 1)

and

2015.02.25 23:27:37.283 ERROR [Thread-3] MidolmanActorsService -  Failed to gracefully stop all actors
java.util.concurrent.TimeoutException: Futures timed out after [2000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.Await$.result(package.scala:116) ~[scala-library-2.11.2.jar:na]
	at org.midonet.midolman.services.MidolmanActorsService.doStop(MidolmanActorsService.scala:117) ~[midolman-2015.03-SNAPSHOT.jar:2015.03-SNAPSHOT]
	at com.google.common.util.concurrent.AbstractService.stop(AbstractService.java:240) [guava-16.0.1.jar:na]
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:218) [guava-16.0.1.jar:na]
	at org.midonet.midolman.services.MidolmanService.doStop(MidolmanService.java:110) [midolman-2015.03-SNAPSHOT.jar:2015.03-SNAPSHOT]
	at com.google.common.util.concurrent.AbstractService.stop(AbstractService.java:240) [guava-16.0.1.jar:na]
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:218) [guava-16.0.1.jar:na]
	at org.midonet.midolman.Midolman.doServicesCleanup(Midolman.java:170) [midolman-2015.03-SNAPSHOT.jar:2015.03-SNAPSHOT]
	at org.midonet.midolman.Midolman.access$000(Midolman.java:54) [midolman-2015.03-SNAPSHOT.jar:2015.03-SNAPSHOT]
	at org.midonet.midolman.Midolman$1.run(Midolman.java:100) [midolman-2015.03-SNAPSHOT.jar:2015.03-SNAPSHOT]
2015.02.25 23:27:37.283 INFO  [Thread-3] MidolmanActorsService -  Stopping the actor system
<<<< mdts.tests.functional_tests.test_bgp.test_icmp_failback (with_bindings connected to uplink #2) ended

also 

2015.02.25 23:29:20.659 DEBUG [midolman-actors.pinned-dispatcher-53] bgp-vty -  setting network
2015.02.25 23:29:20.659 DEBUG [midolman-actors.pinned-dispatcher-53] bgp-vty -  begin, addr: 172.23.0.6, port: 2606
2015.02.25 23:29:20.660 WARN  [midolman-actors.pinned-dispatcher-53] bgp-vty -  bgpd hello message doesn't match expected: "Hello, this is Quagga (version 0.99.22.4)." size: 42
2015.02.25 23:29:20.661 WARN  [midolman-actors.pinned-dispatcher-53] bgp-vty -  bgpd version didn't match expected.
2015.02.25 23:29:20.663 INFO  [midolman-actors.pinned-dispatcher-53] bgp-vty -  doTransaction: router bgp 64513
2015.02.25 23:29:20.663 INFO  [midolman-actors.pinned-dispatcher-53] bgp-vty -  doTransaction: network 172.16.0.0/16
2015.02.25 23:29:20.665 DEBUG [midolman-actors.pinned-dispatcher-53] bgp-vty -  closing connection
2015.02.25 23:29:20.666 DEBUG [midolman-actors.pinned-dispatcher-53] bgp-1 -  (Started) added advertised route: org.midonet.cluster.data.AdRoute{id=6700b706-065a-432b-8875-dfd655682cd1, data=Data{nwPrefix=/172.16.0.0, prefixLength=16, bgpId=cc36fd43-d6ba-4a7f-be25-0910598b5ca7, properties={}}}
2015.02.25 23:29:20.666 DEBUG [midolman-actors.pinned-dispatcher-53] bgp-1 -  (Started) announcing we are BGPD_STATUS active
2015.02.25 23:29:20.666 INFO  [midolman-actors.pinned-dispatcher-53] bgp-1 -  (Started) New BGP session.
2015.02.25 23:29:20.666 ERROR [midolman-actors.pinned-dispatcher-53] bgp-1 -  (Started) Ignoring BGP session 6480b7e6-aa0c-4e70-a9fa-6c879fee6703, only one BGP session per port is supported
2015.02.25 23:29:20.666 INFO  [midolman-actors.pinned-dispatcher-53] bgp-1 -  ({Started}) Advertise: /172.16.0.0/16
2015.02.25 23:29:20.666 DEBUG [midolman-actors.pinned-dispatcher-53] bgp-1 -  (Started) Advertise: unknown BGP 6480b7e6-aa0c-4e70-a9fa-6c879fee6703
2015.02.25 23:29:25.116 DEBUG [midolman-akka.actor.default-dispatcher-2] flow-management -  Removing managed flow ManagedFlow{objref=1294425435, flowMatch=FlowMatch[InputPortNumber=5, EthSrc=ac:ca:ba:b4:3d:e6, EthDst=33:33:00:00:00:16, EtherType=-31011, NetworkSrc=0:0:0:0:0:0:0:0, NetworkDst=ff02:0:0:0:0:0:0:16, NetworkProto=ipv6-icmp, NetworkTTL=1, NetworkTOS=0, FragmentType=None], flowMatch hash=1261303368, creationTimeMillis=1424906956258, lastUsedTimeMillis=1424906956258, hardExpirationMillis=5000, idleExpirationMillis=0, refs=3}
2015.02.25 23:29:25.116 DEBUG [midolman-akka.actor.default-dispatcher-2] flow-management -  Removing managed flow ManagedFlow{objref=1294425435, flowMatch=FlowMatch[InputPortNumber=5, EthSrc=ac:ca:ba:b4:3d:e6, EthDst=33:33:00:00:00:16, EtherType=-31011, NetworkSrc=0:0:0:0:0:0:0:0, NetworkDst=ff02:0:0:0:0:0:0:16, NetworkProto=ipv6-icmp, NetworkTTL=1, NetworkTOS=0, FragmentType=None], flowMatch hash=1261303368, creationTimeMillis=1424906956258, lastUsedTimeMillis=1424906956258, hardExpirationMillis=5000, idleExpirationMillis=0, refs=2} for hard expiration, expired 3858 ms ago

Patch-set: 6
Label: Code-Review=0