Missing dependency in MidoNet Cluster
This patch adds the `hibernate-validator` package to the MidoNet
Cluster dependencies, which is required for the compatibility API
minion, and to prevent its failure with:

javax.validation.ValidationException: Unable to find a default
provider

Change-Id: I4179fcd380e6d4f884b8968681c8e223a325ff4b
Signed-off-by: Alex Bikfalvi <alex.bikfalvi@midokura.com>