Fix netlink channel leak
Recover all NetlinkException protectively ensuring that all netlink
channels are closed; ENODEV errors can possibly happen, so that
memory and file descriptor leak had happened, for instance,

2014.04.10 06:04:52.741 ERROR [MidolmanActors-akka.actor.default-dispatcher-2] DatapathController - akka://MidolmanActors/user/midolman/DatapathController Port operation failed: DpPortDeleteNetdev(DpPort{portNo=4, type=NetDev, name='mbgp1', stats=Stats{rxPackets=0, txPackets=0, rxBytes=0, txBytes=0, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}},null)
org.midonet.netlink.exceptions.NetlinkException: [19] No such device
	at org.midonet.netlink.AbstractNetlinkConnection.processReadFromChannel(AbstractNetlinkConnection.java:392) ~[netlink-1.4.0-SNAPSHOT.jar:na]
	at org.midonet.netlink.AbstractNetlinkConnection.handleReadEvent(AbstractNetlinkConnection.java:308) ~[netlink-1.4.0-SNAPSHOT.jar:na]
	at org.midonet.midolman.io.SelectorThreadPair$1.handleEvent(SelectorThreadPair.java:89) ~[midolman-1.4.0-SNAPSHOT.jar:na]
	at org.midonet.util.eventloop.SimpleSelectLoop.doLoop(SimpleSelectLoop.java:230) ~[midonet-util-1.4.0-SNAPSHOT.jar:na]
	at org.midonet.midolman.io.SelectorThreadPair$3.run(SelectorThreadPair.java:183) ~[midolman-1.4.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_51]

Related-To: MN-1567

Change-Id: Ic7fa29724b0cf6555da84d00a89630adb82b41e3
Signed-off-by: Takayuki Usui <takayuki@midokura.com>